### ISSUE TITLE
Wordpress Export (Demo Data)

### ISSUE THREAD

**Issue by IntrovertedFL** [awsmin/f1#1]
Can we get a copy of the demo data used @ https://staging2.awsm.in/fone?

**Comment by VinuRaj** [comment]
Yup, please find the attached complete WordPress export data [awsmf1-frontitywordpresstheme.WordPress.2020-09-15.xml.zip](https://github.com/awsmin/f1/files/5222693/awsmf1-frontitywordpresstheme.WordPress.2020-09-15.xml.zip)

You may also want this Plugins

 - Contact Form 7
 -  WP Job Openings 
 - [WP Job Openings REST API](https://github.com/awsmin/wp-job-openings-rest-api-example)

The current URL path will be - https://staging2.awsm.in/fone , which you may need to change asper your WordPress setup.

**Comment by IntrovertedFL** [comment]
Thank you @VinuRaj 👍
