### ISSUE TITLE
Accessing different values on returned data

### ISSUE THREAD

**Issue by NatClamp** [awsmin/f1#2]
https://github.com/awsmin/f1/blob/ad2adf972b4db6a21622d7e9b29de7606cebc6d0/packages/f1/src/components/index.js#L54

Hello!
I have a quick question - sorry, I'm new to using Frontity - I was just wondering how you used this bit of code to render a new component:
<Jobs when={data.isAwsmJobOpenings} />
I'd like to do a similar thing but how did you get the .isAwwsmJobOpenings key/value in the data object? Is this something that's set up on your wordpress site, or have you set it to be able to access within your Frontity app?
Sorry if that doesn't make sense, I mean, for example I want to do:
<Shop when={data.isShop} />
to render the Shop component if the user is on /shop/ but there's no .isShop on data...

I know I could conditionally render the component based off the current route, but I was just curious as to how you did it with .isAwsmJobOpenings

Thanks!

**Comment by anantajitjg** [comment]
This is automatically generated by the source package of Frontity(`@frontity/wp-source`) based on the post type. Our theme supports the **WP Job Openings** (https://wpjobopenings.com/) plugin. The post type used to register the jobs is `awsm_job_openings`. So, when you access the job detail page, Frontity will automatically generate this property for you based on the post type. Hence, `isAwsmJobOpenings` (**_is\<typeCapitalized\>_**). So, if you have registered a custom post type named 'shop,' then if you access the shop detail page, you will get isShop in the frontity state (frontity.state.source.data). If not, you won't get this property. Also, for archive pages, you will get **_is\<typeCapitalized\>Archive_** property in the state.

https://github.com/frontity/frontity/blob/114bd4bbe87c99d4384a5fb3eb338ae6d72b67a0/packages/wp-source/src/libraries/handlers/postType.ts#L113

https://github.com/frontity/frontity/blob/114bd4bbe87c99d4384a5fb3eb338ae6d72b67a0/packages/wp-source/src/libraries/handlers/postTypeArchive.ts#L76

**Tip:** In the browser console access the `frontity.state.source.data` object to get all the available properties.

We hope this helps 🙂

**Comment by NatClamp** [comment]
Thank you for such a clear and quick response! Helps so much 🙂
