### ISSUE TITLE
The name of the theme is not a valid npm package name.

### ISSUE THREAD

**Issue by kasperaamodt** [awsmin/f1#3]
Hi!

When i try to install the theme, i get the error message: The name of the theme is not a valid npm package name. Have you removed the package?

**Comment by VinuRaj** [comment]
Hi, thanks for trying out the theme.
The package is available at https://www.npmjs.com/package/@awsmin/f1

Could you share the git repository with us, so that we can have a closer look at what may have gone wrong in your installation.
