### ISSUE TITLE
Adding Logo

### ISSUE THREAD

**Issue by IntrovertedFL** [awsmin/f1#4]
I would like to replace the logo text with an image, Can you suggest the best way? Thanks in advance

**Comment by VinuRaj** [comment]
You can do two thing -

- Easy way is to add the logo/image by directly editing the header.js (in the F1 package (inside components)) and replacing the text with the image (add the image by creating an asset folder inside the package itself and import it to header.js).
- Or, you could build a custom field using ACF pro ( steps — https://community.frontity.org/t/acf-options-page/767/7)

**Comment by IntrovertedFL** [comment]
Thank you :)
