### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by ZeroEcks** [awsmin/f1#6]
Hello, I have modified this for my website but I am unsure which license you have this under? Do I need to publish the source code or leave credit?

**Comment by aravindajith** [comment]
The theme comes under Apache License 2.0. You do not have to publish the source code or leave credits. But I would really appreciate it if you could share the link to your website with us.

**Comment by ZeroEcks** [comment]
Hello! You can see our website at https://sequr.homes

Its being pretty heavily modified but your base was super helpful :)
